@HostAddress = http://localhost:5041/api
@UsernameValid = adam
@PasswordValid = 12345678
@TokenValid = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZGFtIiwianRpIjoiOGQ1ZGQxNWUtNmYwOS00NmY1LTgyZjYtMjUxZTM1MzUyN2Q4IiwiZXhwIjoxNzM4OTI2NzQ3LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo1MDQxIiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTA0MSJ9.-K5e3pcuwoeAlL9Gs0KklqYBnSkEQa13c0bzox89-fc

### Register new user
# Register
POST {{HostAddress}}/auth/register
Accept: application/json
Content-Type: application/json

{
    "fullname": "",
    "email": "",
    "password": "{{PasswordValid}}"
}

### User login
# Login
POST {{HostAddress}}/auth/login
Accept: application/json
Content-Type: application/json

{
    "username": "{{UsernameValid}}",
    "password": "{{PasswordValid}}"
}

### Get authorized profile
# AuthProfile
GET {{HostAddress}}/user/profile
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{TokenValid}}

### Get profile
# UserProfile
GET {{HostAddress}}/user/profile/{{UsernameValid}}
Accept: application/json

### Get posts
# GetPosts
GET {{HostAddress}}/post/?limit=8&author=bella
Accept: application/json

### Create posts
# CreatePost
POST {{HostAddress}}/post
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{TokenValid}}

{
    "Content": "This my other post.\n\n#newpost #test #tester"
}